# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/pyproject.toml"
    schedule:
      interval: "daily" # <-- remove this line and uncomment the weekly schedule underneath if the results are fine
      #interval: "weekly"
      #day: "monday"
      #time: "07:00"
    commit-message:
      prefix: "deps(dependabot)"
  - package-ecosystem: "docker" 
    directory: "/" 
    schedule:
      interval: "weekly"
      day: monday
      time: "07:00"
    commit-message:
      prefix: "deps(dependabot)"
  - package-ecosystem: "github-actions" 
    directory: "/" 
    schedule:
      interval: "weekly"
      day: monday
      time: "07:00"
    commit-message:
      prefix: "deps(dependabot)"
