[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "Kyma-Companion-Blackbox-Tests"
version = "0.1.0"
description = "Kyma Companion Blackbox Tests"
readme = "README.md"
license = "Apache-2.0"
authors = [
  { name = "Muhammad Faizan", email = "m.faizan@sap.com" },
  { name = "Friedrich Wilken", email = "jens.wilken@sap.com" },
  { name = "Mansur Uralov", email = "m.uralov@sap.com" },
  { name = "Mohammad Tanweer Salah", email = "mohammad.tanweer.salah@sap.com" },
]
requires-python = "==3.14.*"
dependencies = [
  "cryptography (>=50.0.0,<51.0.0)",
  "github-action-utils (>=1.1.0,<2.0.0)",
  "python-decouple (>=3.8,<4.0)",
  "redis (>=8.0.1,<9.0.0)",
  "requests (>=2.34.2,<3.0.0)",
  "httpx (>=0.28.1,<0.29.0)",
  "langchain-openai (>=1.3.5,<2.0.0)"
]
[tool.poetry]
package-mode = false

[tool.poetry.group.test.dependencies]
deepeval = {version = "^4.1.0"}
fakeredis = "^2.36.2"
prettytable = "^3.18.0"
pytest = "^9.1.1"
pytest-asyncio = "^1.4.0"
pytest-dotenv = "^0.5.2"
pytest-mock = "^3.15.1"
pytest-rerunfailures = "^16.3"
pyyaml = "^6.0.3"
termcolor = "^3.3.0"
types-pyyaml = "^6.0.12.20260518"

[tool.poetry.group.dev.dependencies]
ipython = "^9.15.0"
mypy = "^2.3.0"
poethepoet = "^0.48.0"
poetry-plugin-sort = "^0.3.0"
ruff = "^0.16.3"
types-requests = "^2.33.0.20260712"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
pythonpath = ["src"]
testpaths = ["tests"]
env_files = [".env.test"]
asyncio_default_fixture_loop_scope = "function"

[tool.poe.tasks]
lint = "ruff check ."
typecheck = "mypy . --pretty"
format = "ruff format . --check"
codecheck = ["lint", "typecheck", "format"]
format-fix = "ruff format ."
lint-fix = "ruff check . --fix"
code-fix = ["format-fix", "lint-fix"]
sort = "poetry sort"
lock-check = "bash ${POE_ROOT}/../../scripts/shell/lock-check.sh"
lock-fix = "bash ${POE_ROOT}/../../scripts/shell/lock-sync.sh"
pre-commit-check = ["sort", "code-fix", "lock-check", "codecheck"]
run-evaluation = "python src/run_evaluation.py"
run-a2a-evaluation = "python src/run_a2a_evaluation.py"
