"""Unit tests for KymaReActAgent.ainvoke() response content extraction.

Verifies that the agent correctly extracts plain text from AIMessage.content
regardless of whether the underlying model returns a plain string (OpenAI Chat
Completions) or a list of content blocks (Bedrock/Anthropic, Gemini).

Content block formats used as test fixtures:

Anthropic / AWS Bedrock Converse:
  AIMessage.content is a list of typed dicts.
  Source: https://platform.claude.com/docs/en/api/messages
  Quote: "Content generated by the model. This is an array of content blocks,
          each of which has a type that determines its shape."
  Observed in langchain-aws source (ChatBedrockConverse docstring, line 58):
    AIMessage(content=[{'type': 'text', 'text': "J'aime la programmation."}], ...)

Google Gemini:
  AIMessage.content is also a list of typed dicts when the response contains
  non-plain-text blocks (e.g. thinking, tool use).
  Source: https://ai.google.dev/api/generate-content
  Quote: response text is nested as candidates[0].content.parts[0].text,
         never a top-level string.
  Observed in langchain-google-genai source (chat_models.py, _parse_response_candidate):
    content = [{"type": "text", "text": "..."}]  when parts contain text blocks.
"""

from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from langchain_core.embeddings import Embeddings
from langchain_core.messages import AIMessage

from agents.kyma.react_agent import KymaReActAgent
from services.k8s import IK8sClient
from utils.models.factory import IModel
from utils.settings import MAIN_EMBEDDING_MODEL_NAME, MAIN_MODEL_NAME

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def mock_models() -> dict:
    """Minimal model stubs — no real LLM calls are made."""
    llm_stub = MagicMock()
    model_stub = MagicMock(spec=IModel)
    model_stub.llm = llm_stub

    embedding_stub = MagicMock(spec=Embeddings)

    return {
        MAIN_MODEL_NAME: model_stub,
        MAIN_EMBEDDING_MODEL_NAME: embedding_stub,
    }


@pytest.fixture
def mock_k8s_client() -> MagicMock:
    """Stubbed K8s client — no cluster calls are made."""
    return MagicMock(spec=IK8sClient)


@pytest.fixture
def agent(mock_models: dict, mock_k8s_client: MagicMock) -> KymaReActAgent:
    """KymaReActAgent with all external dependencies stubbed out."""
    search_tool_stub = MagicMock()
    with (
        patch("agents.kyma.react_agent.SearchKymaDocTool", return_value=search_tool_stub),
        patch("agents.kyma.react_agent.create_agent") as mock_create_agent,
    ):
        mock_graph = MagicMock()
        mock_create_agent.return_value = mock_graph
        instance = KymaReActAgent(
            models=mock_models,
            k8s_client=mock_k8s_client,
        )
        return instance


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _set_graph_response(agent: KymaReActAgent, ai_message: AIMessage) -> None:
    """Point the agent's internal graph at an AsyncMock returning the given message."""
    agent._graph.ainvoke = AsyncMock(return_value={"messages": [ai_message]})


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_openai_plain_string_content(agent: KymaReActAgent) -> None:
    """OpenAI Chat Completions returns content as a plain string.

    The agent must pass it through unchanged.
    """
    _set_graph_response(agent, AIMessage(content="Your pod is crashing."))

    result = await agent.ainvoke("Why is my pod crashing?")

    assert result == "Your pod is crashing."


@pytest.mark.asyncio
async def test_anthropic_bedrock_list_content(agent: KymaReActAgent) -> None:
    """Anthropic via AWS Bedrock Converse returns content as a list of typed dicts.

    Format source: https://platform.claude.com/docs/en/api/messages
    "Content generated by the model. This is an array of content blocks,
     each of which has a type that determines its shape."

    Fixture matches the exact structure documented in the langchain-aws
    ChatBedrockConverse docstring:
      AIMessage(content=[{'type': 'text', 'text': "..."}])
    """
    _set_graph_response(
        agent,
        AIMessage(content=[{"type": "text", "text": "Your pod is crashing."}]),
    )

    result = await agent.ainvoke("Why is my pod crashing?")

    assert result == "Your pod is crashing."


@pytest.mark.asyncio
async def test_anthropic_extended_thinking_list_content(agent: KymaReActAgent) -> None:
    """Anthropic with extended thinking enabled returns a thinking block before the text block.

    Format source: https://platform.claude.com/docs/en/api/messages
    The content array can contain ThinkingBlock objects with type="thinking"
    followed by TextBlock objects with type="text".

    The agent must return only the text, discarding the thinking block.
    """
    _set_graph_response(
        agent,
        AIMessage(
            content=[
                {"type": "thinking", "thinking": "Let me analyze the pod status..."},
                {"type": "text", "text": "Your pod is crashing."},
            ]
        ),
    )

    result = await agent.ainvoke("Why is my pod crashing?")

    assert result == "Your pod is crashing."


@pytest.mark.asyncio
async def test_gemini_list_content(agent: KymaReActAgent) -> None:
    """Google Gemini returns content as a list of typed dicts via langchain-google-genai.

    Format source: https://ai.google.dev/api/generate-content
    Response text is nested as candidates[0].content.parts[0].text.
    The langchain-google-genai integration maps this to:
      AIMessage(content=[{"type": "text", "text": "..."}])

    Observed in langchain-google-genai chat_models.py (_parse_response_candidate):
      content is built as a list when parts contain text blocks.
    """
    _set_graph_response(
        agent,
        AIMessage(content=[{"type": "text", "text": "Your pod is crashing."}]),
    )

    result = await agent.ainvoke("Why is my pod crashing?")

    assert result == "Your pod is crashing."


@pytest.mark.asyncio
async def test_list_content_is_not_returned_as_python_repr(agent: KymaReActAgent) -> None:
    """Regression guard: str() on a list returns a Python repr, not the text.

    This test explicitly asserts that the old broken behaviour no longer occurs.
    Previously: str([{'type': 'text', 'text': 'answer'}]) == "[{'type': 'text', 'text': 'answer'}]"
    """
    answer = "Your pod is crashing."
    broken_repr = str([{"type": "text", "text": answer}])

    _set_graph_response(
        agent,
        AIMessage(content=[{"type": "text", "text": answer}]),
    )

    result = await agent.ainvoke("Why is my pod crashing?")

    assert result != broken_repr
    assert result == answer
