name: "API Tests"
run-name: "API Tests for PR #${{ github.event.number }}"

on:
  pull_request_target:
    types: [labeled, opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - "src/routers/**"
      - "src/agents/**/tools/**"
      - "tests/blackbox/src/api_tests/**"
      - ".github/workflows/pull-api-tests.yaml"
      - ".github/workflows/evaluation-test-reusable.yaml"

permissions: read-all

jobs:
  authorize:
    runs-on: ubuntu-latest
    steps:
      - name: Check codeowner authorization
        uses: kyma-project/kyma-companion/.github/actions/check-codeowner-auth@main
        with:
          github-token: ${{ secrets.GIT_BOT_TOKEN }}

  wait-for-build:
    name: Wait for image build job
    needs: authorize
    if: contains(github.event.pull_request.labels.*.name, 'api-tests')
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build
        uses: kyma-project/kyma-companion/.github/actions/wait-for-build@main
        with:
          git-ref: ${{ github.event.pull_request.head.sha }}
          check-run-name: "build / Build image"

  api-tests:
    name: Run API tests
    uses: kyma-project/kyma-companion/.github/workflows/evaluation-test-reusable.yaml@main
    needs: wait-for-build
    secrets: inherit
    with:
      IMAGE_NAME: "europe-docker.pkg.dev/kyma-project/dev/kyma-companion:PR-${{ github.event.number }}"
      TEST_REPO_FULLNAME: ${{ github.event.pull_request.head.repo.full_name }}
      TEST_REF: ${{ github.event.pull_request.head.ref }}
      RUN_EVALUATION_TESTS: false
