name: "E2E Tests for Doc Indexer"
run-name: "E2E Tests for Doc Indexer PR #${{ github.event.number }}"

on:
  pull_request_target:
    types: [labeled, opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - "doc_indexer/**"
      - ".github/workflows/pull-e2e-tests-doc-indexer.yaml"
      - ".github/workflows/e2e-tests-doc-indexer-reusable.yaml"

permissions: read-all

jobs:
  authorize:
    runs-on: ubuntu-latest
    steps:
      - name: Check codeowner authorization
        uses: kyma-project/kyma-companion/.github/actions/check-codeowner-auth@main
        with:
          github-token: ${{ secrets.GIT_BOT_TOKEN }}

  wait-for-build:
    name: Wait for image build job
    needs: authorize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install requirements
        run: |
          pip install -r ./scripts/python/wait-for-commit-check/requirements.txt

      - name: Wait for build
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GIT_REF: ${{ github.event.pull_request.head.sha }}
          REPOSITORY_FULL_NAME: "${{ github.repository }}"
          GIT_CHECK_RUN_NAME: "build / Build image"
          INTERVAL: 60
          TIMEOUT: 900
        run: |
          python ./scripts/python/wait-for-commit-check/run.py

  e2e-tests:
    name: Run e2e tests
    uses: kyma-project/kyma-companion/.github/workflows/e2e-tests-doc-indexer-reusable.yaml@main
    needs: wait-for-build
    secrets: inherit
    with:
      IMAGE_NAME: "europe-docker.pkg.dev/kyma-project/dev/kyma-companion-indexer:PR-${{ github.event.number }}"
      DOCS_TABLE_NAME: "kc_pr_${{ github.event.number }}_e2e"
