name: "E2E Tests for Doc Indexer"
run-name: "E2E Tests for Doc Indexer"

on:
  workflow_run:
    workflows: ["Pull Build Image for Indexer"]
    types: [completed]

permissions: read-all

jobs:
  e2e-tests:
    name: Run e2e tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: kyma-project/kyma-companion/.github/workflows/e2e-tests-doc-indexer-reusable.yaml@main
    secrets: inherit
    with:
      IMAGE_NAME: "europe-docker.pkg.dev/kyma-project/dev/kyma-companion-indexer:PR-${{ github.event.workflow_run.pull_requests[0].number }}"
      DOCS_TABLE_NAME: "kc_pr_${{ github.event.workflow_run.pull_requests[0].number }}_e2e"
