name: Pull Build Image for Indexer

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - "main"
    paths:
      - "doc_indexer/**"
      - ".github/workflows/pull-build-image-indexer.yaml"

permissions: read-all

jobs:
  authorize:
    runs-on: ubuntu-latest
    steps:
      - name: Check codeowner authorization
        uses: kyma-project/kyma-companion/.github/actions/check-codeowner-auth@main
        with:
          github-token: ${{ secrets.GIT_BOT_TOKEN }}

  build-indexer:
    needs: authorize
    permissions:
      id-token: write # This is required for requesting the JWT token
      contents: read # This is required for actions/checkout
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: kyma-companion-indexer
      dockerfile: Dockerfile
      context: ./doc_indexer
      export-tags: true
      platforms: |
        linux/amd64
