name: Push Build Image

on:
  push:
    branches:
      - "main"
      - "release-*"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  compute-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get_tag.outputs.TAGS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Get the latest tag
        id: get_tag
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          {
            echo 'TAGS<<EOF'
            echo "${{ github.sha }}"
            echo "${REF_NAME}"
            if [[ "${REF_NAME}" == "main" ]]; then
              echo "latest"
            elif [[ "${REF_NAME}" == release-* ]]; then
              echo "rc"
            fi
            echo EOF
          } >> "$GITHUB_OUTPUT"
  build:
    needs: compute-tags
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: kyma-companion
      dockerfile: Dockerfile
      context: .
      tags: ${{ needs.compute-tags.outputs.tags }}
      platforms: |
        linux/amd64
