name: Push Build Image LangFuse Worker

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile.langfuse-worker"


permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout


jobs:
  build:
    uses: kyma-project/kyma-companion/.github/workflows/build-langfuse-reuseable.yaml@main
    with:
      IMAGE_NAME: external-langfuse-worker
      DOCKERFILE: Dockerfile.langfuse-worker
