name: Push E2E Tests for Indexer

on:
  workflow_run:
    workflows: ["Push Build Image for Indexer"]
    types: [completed]
    branches:
      - "main"
      - "release-*"

permissions: read-all

jobs:
  e2e-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: kyma-project/kyma-companion/.github/workflows/e2e-tests-doc-indexer-reusable.yaml@main
    secrets: inherit
    with:
      IMAGE_NAME: "${{ vars.IMAGE_NAME_INDEXER }}:${{ github.event.workflow_run.head_branch }}"
      DOCS_TABLE_NAME: "kc_push_${{ github.event.workflow_run.head_sha }}_e2e"
